//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OEMRSysOption
    {
        public int ID { get; set; }
        public string OptionCode { get; set; }
        public string OptionName { get; set; }
        public string OptionValue { get; set; }
        public int OptionIsValidity { get; set; }
        public string OptionRemark { get; set; }
        public string OptionRemark1 { get; set; }
        public string OptionRemark2 { get; set; }
        public string OptionRemark3 { get; set; }
        public string OptionRemark4 { get; set; }
        public string OptionRemark5 { get; set; }
        public string OptionRemark6 { get; set; }
    }
}
