//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OEMRSysMenu
    {
        public int ID { get; set; }
        public string MenuName { get; set; }
        public string MenuShowName { get; set; }
        public Nullable<int> MenuLevel { get; set; }
        public string MenuLink { get; set; }
        public string MenuIcon { get; set; }
        public string MenuSort { get; set; }
        public Nullable<int> MenuIsValidity { get; set; }
        public string MenuRemark { get; set; }
        public string MenuRemark1 { get; set; }
        public string MenuRemark2 { get; set; }
        public string MenuRemark3 { get; set; }
        public string MenuRemark4 { get; set; }
        public string MenuRemark5 { get; set; }
        public string MenuRemark6 { get; set; }
    }
}
