//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OEMRSysDictionry
    {
        public int ID { get; set; }
        public string DicCode { get; set; }
        public string DicName { get; set; }
        public string DicValue { get; set; }
        public string DicShowValue { get; set; }
        public string DicIsValidity { get; set; }
        public string DicRemark { get; set; }
        public string DicRemark1 { get; set; }
        public string DicRemark2 { get; set; }
        public string DicRemark3 { get; set; }
        public string DicRemark4 { get; set; }
        public string DicRemark5 { get; set; }
        public string DicRemark6 { get; set; }
    }
}
