//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OEMREntities : DbContext
    {
        public OEMREntities()
            : base("name=OEMREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OEMRSysDictionry> OEMRSysDictionry { get; set; }
        public virtual DbSet<OEMRSysMenu> OEMRSysMenu { get; set; }
        public virtual DbSet<OEMRSysOption> OEMRSysOption { get; set; }
        public virtual DbSet<OEMRTest> OEMRTest { get; set; }
    }
}
